name: Ultility
version: ${project.version}
main: net.minevn.tranlong5252.Main
api-version: 1.16
authors: [ tranlong5252 ]
commands:
  bruh:
    description: làm chơi
  gl+:
    description: lấy tọa độ có thể copy